### ISSUE TITLE
Deploying ``Broadcast_Support_Relation``  on a Franka Emika robot

### ISSUE THREAD

**Issue by lif314** [lyttttt3333/Broadcast_Support_Relation#3]
Thank you for your great work! I am new to this field. Could you please share the script or relevant materials for deploying your model on a Franka Emika robot? Thank you very much!

**Comment by lyttttt3333** [comment]
All code will be released, approximatedly after Oct . Thanks for your understanding of the heavy load that our main authors are suffering from :(

**Comment by lyttttt3333** [comment]
Thank you very much for your interest in our project! All code will be released in the near future. Thanks for your understanding of the heavy load that our main authors are suffering from.

**Comment by lyttttt3333** [comment]
Thank you very much for your interest in our project! All code will be released in the near future approximately after icra.

**Comment by lif314** [comment]
> Thank you very much for your interest in our project! All code will be released in the near future approximately after icra.

Thanks! Looking forward to it!
