### ISSUE TITLE
data_generation/data_collection/gen_grasp.py

### ISSUE THREAD

**Issue by yft1996** [lyttttt3333/Broadcast_Support_Relation#4]
Thank you for your great work! 
And I have a question. In your project, I didn't find `data_generation/data_collection/gen_grasp.py` shown in `README.md`, will you upload this file in the future?
Thank you very much!

**Comment by lyttttt3333** [comment]
Thanks for your insterest! Yes we will update this file in the future, since there are some update of IsaacSim and there are some errors in the previous version. So we want to find a better solution. Thanks for your understanding!

**Comment by yft1996** [comment]
Thank you for your contribution and look forward to the completion of this project.
